version: "3.5"
services:

  odoo:
    image: odoo:17.0
    ports:
      - "8069:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    depends_on:
      - db

  apiServer:
    image: apiserver
    container_name: apiservercon
    build:
      context: ./api/
      dockerfile: dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - api_server:/var/lib/apiServer
    depends_on:
      - odoo
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=gomaxtracker
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123456
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - odoo
  #     - apiServer

volumes:
  odoo_data:
  odoo_db_data:
  api_server:
  pgadmin_data: